### ISSUE TITLE
Question on Trajectory Sampling

### ISSUE THREAD

**Issue by Rashfu** [adobe-research/SuperGaussian#1]
Thank you for sharing this amazing project! But I have a question regarding the trajectory sampling process. I wasn’t able to find where this is handled in the codebase—could you clarify how you perform trajectory sampling or point me to the specific section?

Thanks in advance.

**Comment by yshen47** [comment]
Thanks for your questions! Here is one example script to prepare the novel trajectory on MV-Imgnet test. essentially, we first triangulate all camera poses to figure out the scene center. And sample trajectory around the scene center with sinusoid changes on vertical dimensions. 

https://drive.google.com/file/d/10CKoRs6Uwfhwt2ao-T7ST2kLfGvNdH4E/view?usp=sharing
